name: Deploy Vite App

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install dependencies
        run: |
          cd pro-alx-UI
          npm install

      - name: Build Vite app
        run: |
          export WAKA_ID="TFIToZ5WWJ14zwuza5IWKbHh"
          export GITHUB_ID="94a0ffa989a216e4c779"
          export PROALX="https://www.proalx.live"
          export API_URL="https://www.proalx.live/api/v1"
          cd pro-alx-UI
          npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/html/proalx

      - name: Transfer dist directory to server
        run: |
          ls pro-alx-UI/dist
          cd pro-alx-UI
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" > private_key.pem
          mv dist proalx
          sudo scp -i private_key.pem -r proalx "${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/html/proalx"
          rm private_key.pem
